import { getDbClient, runQuery } from "./dal";


async function initDbSchema() {
    const ddl = `
    BEGIN;


CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  token TEXT
);


CREATE TABLE IF NOT EXISTS customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
  CONSTRAINT fk_customer_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  price NUMERIC(12,2) NOT NULL CHECK (price > 0),
  stock INTEGER NOT NULL CHECK (stock >= 0),
  description TEXT
);


CREATE TABLE IF NOT EXISTS product_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  image_path TEXT NOT NULL,
  CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  address TEXT,
  order_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','canceled','shipped')),
  note TEXT,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS orders_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- or drop this and use (order_id, product_id) as PK
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  qty INTEGER NOT NULL CHECK (qty > 0),
  price NUMERIC(12,2) NOT NULL CHECK (price > 0),
  discount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  CONSTRAINT fk_op_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_op_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT
  -- UNIQUE (order_id, product_id) -- uncomment if you want to prevent duplicates
);


CREATE TABLE IF NOT EXISTS category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  parent_id BIGINT,
  CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS product_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  CONSTRAINT fk_pc_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pc_product  FOREIGN KEY (product_id)  REFERENCES product(id)  ON DELETE RESTRICT
);


-- helpful indexes for FKs / lookups
CREATE INDEX IF NOT EXISTS idx_orders_customer_id        ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_product_image_product_id  ON product_image(product_id);
CREATE INDEX IF NOT EXISTS idx_op_order_id               ON orders_product(order_id);
CREATE INDEX IF NOT EXISTS idx_op_product_id             ON orders_product(product_id);
CREATE INDEX IF NOT EXISTS idx_product_category_cat_id   ON product_category(category_id);
CREATE INDEX IF NOT EXISTS idx_product_category_prod_id  ON product_category(product_id);


COMMIT;
`


    await runQuery(ddl, [], undefined);
}

async function generateSampleData(){
    
    const dbClient = await getDbClient();
    try {        
        runQuery("BEGIN;", [], dbClient);            
        runQuery(`INSERT INTO app_user (email, username, password_hash, is_admin) VALUES ('admin@email.com', 'admin', 'admin', true)`);            
        runQuery("COMMIT;", [], dbClient);
    } catch (error) {
        runQuery("ROLLBACK", [], dbClient);
        throw error;
    } finally {
        dbClient.release();
    }


}
// initDbSchema();
generateSampleData();

// import { Database as DB } from "better-sqlite3";
// import { openDb, runQuery } from "./dal";


// function initDbSchema(db: DB): void {

//     const ddl = `

//     CREATE TABLE IF NOT EXISTS "user" (
//     id INTEGER  PRIMARY KEY AUTOINCREMENT,
//     email TEXT NOT NULL UNIQUE,
//     username TEXT NOT NULL,
//     password_hash TEXT NOT NULL,
//     isAdmin INTEGER NOT NULL DEFAULT 0 CHECK (isAdmin IN (0,1)),
//     token TEXT
//     );


//     CREATE TABLE IF NOT EXISTS customer (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     user_id INTEGER UNIQUE,
//     first_name TEXT NOT NULL,
//     last_name TEXT NOT NULL,
//     email TEXT NOT NULL UNIQUE,
//     phone TEXT,
//     created_at TEXT NOT NULL DEFAULT (datetime('now')),

//     FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE RESTRICT
// );

// CREATE TABLE IF NOT EXISTS product (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     sku TEXT NOT NULL UNIQUE,
//     name TEXT NOT NULL,
//     is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0, 1)),
//     price REAL NOT NULL CHECK(price > 0),
//     stock INTEGER NOT NULL CHECK(stock >= 0),
//     description TEXT    
// );

// CREATE TABLE IF NOT EXISTS product_image (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     product_id INTEGER NOT NULL,
//     image_path TEXT NOT NULL,

//     FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
// );

// CREATE TABLE IF NOT EXISTS orders (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     customer_id INTEGER NOT NULL,
//     address TEXT,
//     order_date TEXT NOT NULL DEFAULT (datetime('now')),
//     status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','canceled','shipped')),
//     note TEXT,

//     FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT
// );


// CREATE TABLE IF NOT EXISTS orders_product (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,  -- could be combination of p-id and o-id
//     order_id INTEGER NOT NULL,
//     product_id INTEGER NOT NULL,
//     qty INTEGER NOT NULL CHECK(qty >0),
//     price REAL NOT NULL CHECK(price >0),
//     discount REAL NOT NULL DEFAULT 0 CHECK(discount >= 0),

    
//     FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
//     FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT
// );

// CREATE TABLE IF NOT EXISTS category (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     name TEXT NOT NULL UNIQUE,
//     parent_id INTEGER,

//     FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE RESTRICT
// );

// CREATE TABLE IF NOT EXISTS product_category (
//     id INTEGER PRIMARY KEY AUTOINCREMENT,
//     category_id INTEGER NOT NULL,
//     product_id INTEGER NOT NULL,

//     FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT,
//     FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT
// );


// CREATE INDEX IF NOT EXISTS idx_product_category ON product_category(category_id);
//   `;

//     db.exec("BEGIN");
//     try {
//         db.exec(ddl);
//         db.exec("COMMIT");
//     } catch (e) {
//         db.exec("ROLLBACK");
//         throw e;
//     }
// }

// function generateSampleData() {

//     // --- Categories ---
//     runQuery("INSERT INTO category (name) VALUES ('Electronics');");
//     runQuery("INSERT INTO category (name) VALUES ('Clothing');");
//     runQuery("INSERT INTO category (name) VALUES ('Books');");

//     runQuery("INSERT INTO category (name, parent_id) VALUES ('Laptops', 1);");
//     runQuery("INSERT INTO category (name, parent_id) VALUES ('Smartphones', 1);");

//     // --- Products ---
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1001','Laptop Pro 15','1200.00',10,'High performance laptop')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1002','Laptop Air 13','900.00',15,'Lightweight laptop')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1003','Smartphone X','800.00',20,'Flagship smartphone')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1004','Smartphone Y','600.00',25,'Affordable smartphone')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1005','Wireless Mouse','25.00',100,'Ergonomic wireless mouse')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1006','Mechanical Keyboard','75.00',50,'RGB mechanical keyboard')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1007','Headphones','60.00',40,'Noise cancelling headphones')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1008','Smartwatch','200.00',30,'Fitness smartwatch')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1009','T-Shirt','15.00',80,'Cotton T-shirt')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1010','Jeans','40.00',60,'Denim jeans')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1011','Jacket','70.00',25,'Winter jacket')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1012','Novel A','12.00',100,'Bestselling novel')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1013','Novel B','14.00',90,'Popular novel')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1014','Cookbook','20.00',50,'Healthy recipes cookbook')");
//     runQuery("INSERT INTO product (sku, name, price, stock, description) VALUES ('SKU1015','Children Book','10.00',70,'Kids storybook')");

//     // --- Product-Category mapping ---
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (1,4)"); //--Laptop Pro -> Laptops
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (2,4)"); //--Laptop Air -> Laptops
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (3,5)"); //--Smartphone X -> Smartphones
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (4,5)"); //--Smartphone Y -> Smartphones
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (5,1)"); //--Mouse -> Electronics
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (6,1)"); //--Keyboard -> Electronics
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (7,1)"); //--Headphones -> Electronics
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (8,1)"); //--Smartwatch -> Electronics
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (9,2)"); //--T - shirt -> Clothing
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (10,2)"); //--Jeans -> Clothing
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (11,2)"); //--Jacket -> Clothing
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (12,3)"); //--Novel A -> Books
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (13,3)"); //--Novel B -> Books
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (14,3)"); //--Cookbook -> Books
//     runQuery("INSERT INTO product_category (product_id, category_id) VALUES (15,3)"); //--Children Book -> Books

//     // --- users  ---
//     runQuery(`INSERT INTO "user" (email, username, password_hash, isAdmin) VALUES ('admin@email.com', 'admin', 'admin', 1)`);
//     runQuery(`INSERT INTO "user" (email, username, password_hash, isAdmin) VALUES ('u1@email.com', 'u1', '1234', 0)`);
//     runQuery(`INSERT INTO "user" (email, username, password_hash, isAdmin) VALUES ('u2@email.com', 'u2', '1234', 0)`);
//     runQuery(`INSERT INTO "user" (email, username, password_hash, isAdmin) VALUES ('u3@email.com', 'u3', '1234', 0)`);
//     runQuery(`INSERT INTO "user" (email, username, password_hash, isAdmin) VALUES ('u4@email.com', 'u4', '1234', 0)`);

//     // --- Customers ---
//     runQuery("INSERT INTO customer (first_name, last_name, email, phone, user_id) VALUES ('Alice','Smith','alice@example.com','111-222-3333', 2)");
//     runQuery("INSERT INTO customer (first_name, last_name, email, phone, user_id) VALUES ('Bob','Johnson','bob@example.com','222-333-4444', 3)");
//     runQuery("INSERT INTO customer (first_name, last_name, email, phone, user_id) VALUES ('Carol','Williams','carol@example.com','333-444-5555', 4)");
//     runQuery("INSERT INTO customer (first_name, last_name, email, phone, user_id) VALUES ('David','Brown','david@example.com','444-555-6666', 5)");

//     // --- Orders ---
//     runQuery("INSERT INTO orders (customer_id, address, status, note) VALUES (1,'123 Main St','new','First order by Alice')");
//     runQuery("INSERT INTO orders (customer_id, address, status, note) VALUES (2,'456 Park Ave','shipped','Bob order shipped')");
//     runQuery("INSERT INTO orders (customer_id, address, status, note) VALUES (3,'789 Oak Rd','new','Carol new order')");
//     runQuery("INSERT INTO orders (customer_id, address, status, note) VALUES (4,'321 Pine Ln','canceled','David canceled order')");
//     runQuery("INSERT INTO orders (customer_id, address, status, note) VALUES (1,'123 Main St','shipped','Alice second order')");
//     runQuery("INSERT INTO orders (customer_id, address, status, note) VALUES (2,'456 Park Ave','new','Bob second order')");

//     // --- Orders_Product ---
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (1,1,1,1200)"); //Alice bought Laptop Pro
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (1,5,2,25)"); //Alice added 2 mice
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (2,3,1,800)"); //Bob bought Smartphone X
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (2,7,1,60)"); //Bob added headphones
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (3,9,3,15)"); //Carol bought T - shirts
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (4,10,1,40)"); //David ordered jeans(later canceled)
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (5,2,1,900)"); //Alice bought Laptop Air
//     runQuery("INSERT INTO orders_product (order_id, product_id, qty, price) VALUES (6,12,2,12)"); //Bob bought 2 novels

    
// }

// console.log("Starting init DB");

// openDb().then((db)=>{
//     initDbSchema(db);
//     console.log("Done init DB");
// })
// // generateSampleData();

