import { appConfig } from "../utils/config";
import { getDbClient, runQuery } from "./dal";
import bcrypt from "bcrypt"

async function initDbSchema() {
    const ddl = `
    BEGIN;


CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  token TEXT
);


CREATE TABLE IF NOT EXISTS customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    
  CONSTRAINT fk_customer_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  price NUMERIC(12,2) NOT NULL CHECK (price > 0),
  stock INTEGER NOT NULL CHECK (stock >= 0),
  description TEXT
);


CREATE TABLE IF NOT EXISTS product_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  image_path TEXT NOT NULL,
  CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  address TEXT,
  order_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','canceled','shipped')),
  note TEXT,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS orders_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- or drop this and use (order_id, product_id) as PK
  order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  qty INTEGER NOT NULL CHECK (qty > 0),
  price NUMERIC(12,2) NOT NULL CHECK (price > 0),
  discount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  CONSTRAINT fk_op_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_op_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT
  -- UNIQUE (order_id, product_id) -- uncomment if you want to prevent duplicates
);


CREATE TABLE IF NOT EXISTS category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  parent_id BIGINT,
  CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS product_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  CONSTRAINT fk_pc_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pc_product  FOREIGN KEY (product_id)  REFERENCES product(id)  ON DELETE RESTRICT
);


-- helpful indexes for FKs / lookups
CREATE INDEX IF NOT EXISTS idx_orders_customer_id        ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_product_image_product_id  ON product_image(product_id);
CREATE INDEX IF NOT EXISTS idx_op_order_id               ON orders_product(order_id);
CREATE INDEX IF NOT EXISTS idx_op_product_id             ON orders_product(product_id);
CREATE INDEX IF NOT EXISTS idx_product_category_cat_id   ON product_category(category_id);
CREATE INDEX IF NOT EXISTS idx_product_category_prod_id  ON product_category(product_id);


COMMIT;
`


    await runQuery(ddl, [], undefined);
}

async function generateSampleData(){
    
    const dbClient = await getDbClient();
    try {        
        const passwordHash = await bcrypt.hash("admin" + process.env.HASH_PEPPER, 12)
        runQuery("BEGIN;", [], dbClient);            
        runQuery(`INSERT INTO app_user (email, username, password_hash, is_admin) VALUES ('admin@email.com', 'admin', '${passwordHash}', true)`);            
        runQuery("COMMIT;", [], dbClient);
    } catch (error) {
        runQuery("ROLLBACK", [], dbClient);
        throw error;
    } finally {
        dbClient.release();
    }


}

// initDbSchema();
// generateSampleData();

console.log(appConfig.DB_URL);
